modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT License"
[[mods]]
modId = "hyperios" #mandatory
version = "0.0.1-1.19.4" #mandatory
displayName = "Hyperios" #mandatory
logoFile = "icon.png" #optional
credits = "Thanks for playing" #optional
authors = "Hardel" #optional

description = '''
Introducing "Hyperios," the core mod of our immersive Minecraft modpack.

This enchanting mod brings a unique blend of magic, astrology, and space exploration to your gaming experience.
Immerse yourself in an engaging visual novel and uncover the captivating storylines hidden within.
Hyperios offers a vast array of new items and magical tools to aid you on your cosmic journey.
Unravel the mysteries of the stars, harness the power of celestial energies, and become a true master of the arcane arts in this otherworldly adventure.
Are you ready to embark on an epic quest through the cosmos? Dive into the mesmerizing world of Hyperios and let the magic unfold!
'''
[[dependencies.hyperios]] #optional
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hyperios]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
